### ISSUE TITLE
Protobuf changed in 0.17.8

### ISSUE THREAD

**Issue by or-else** [tinode/csharpbot#12]
Please update. Thanks!

https://github.com/tinode/chat/commit/f81afc2d0d27097873c84b06f96a48cdf29e1540#diff-c39e30a4b1fa6a614532a7e58fb319214f6b61336eba5a61f2494dd8c084d42d

**Comment by BenDerPan** [comment]
I will make it next week :)

**Comment by BenDerPan** [comment]
sorry for late, now finished. :)
