### ISSUE TITLE
Grpc disconnecting

### ISSUE THREAD

**Issue by sharpsalat** [tinode/csharpbot#6]
Hello, i have a problem with connecting to server.
My bot receiving MSG from tcp in another thread, and sends it to Tinode server by event.
But after some sending or time it disconnecting without any logs. 
Maybe it depends on type of login (by secret) or big time between sending or Threads errors.
In Telegram all message are received without problem

        private static void TextSBDMessage(SatteliteMessage Message)
        {
            var textMessage = "Ошибка получения сообщения";
            var date = DateTime.MinValue;
            try
            {
                var enc1251 = Encoding.GetEncoding(1251);
                textMessage = enc1251.GetString(Message.Payload.Skip(9).ToArray());
                date = DateTime.FromBinary(BitConverter.ToInt64(Message.Payload.Skip(1).Take(8).ToArray()));
                tg.SendTextMessageAsync(id, "MessageText: " + textMessage  + "\nDate: " + date);
                Console.WriteLine("MessageText: " + textMessage + "\nDate: " + date);
                
            }
            catch (Exception)
            {
                tg.SendTextMessageAsync(id, "Error in decoding");
                return;
            }

            try
            {
                var tmsg = new MsgBuilder();
                tmsg.AppendTextLine(textMessage, isForm: true, isBold: true);
                tmsg.AppendTextLine(date.ToString());
                bot.ClientPost(bot.Publish("grp74z-fnQmbm8", tmsg.Message));
            }
            catch (Exception)
            {
                tg.SendTextMessageAsync(id, "Error with Tinode sending!!");
            }
        }

        private static void Main()
        {
            var tg = new TelegramBotClient(tgId);
            tg.SendTextMessageAsync(id, "SBD logger started");
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Console.CancelKeyPress += Console_CancelKeyPress;
            bot = new ChatBot(server, local, schema: "basic", secret: secret);

            bot.ServerDataEvent += Bot_ServerDataEvent;
            bot.ServerMetaEvent += Bot_ServerMetaEvent;
            bot.ServerPresEvent += Bot_ServerPresEvent;
            bot.CtrlMessageEvent += Bot_CtrlMessageEvent;
            bot.LoginSuccessEvent += Bot_LoginSuccessEvent;
            bot.LoginFailedEvent += Bot_LoginFailedEvent;
            bot.DisconnectedEvent += Bot_DisconnectedEvent;

            //  bot.BotResponse = new BotReponse(bot);
            net.OnMessageReceived += OnSBDMessageReceived;

            bot.Start().Wait(); }

**Comment by BenDerPan** [comment]
@MyOnAsSalat Hi，I noticed this, If there is no data  sent or received over a period of time, then the connection will dead, I am not sure if this is a grpc strategy, but you can keep sending message to any userID to avoid this, for example: you can send to a userID every 30 seconds.  besides, if you send a big message which beyond  the limitation of tinode server, the connection will broken down, too. and you can change the config size much bigger at server side to solve this.

**Comment by sharpsalat** [comment]
Oh okay thx for advice, i think i can make user account for trash :D
Have that bot way to check connection? I see event with it.

     private static void Bot_DisconnectedEvent(object sender, EventArgs e)
        {
            tg.SendTextMessageAsync(id, "Disconnected: ");
            bot = new ChatBot(server, local, schema: "basic", secret: secret);
        }
But this event doesn't triggered by diconnecting after big time.
I mean have we a way to auto reconnect to the server after any error and check message that haven't been sended to resend it again?

**Comment by BenDerPan** [comment]
yes, that's a good idea, but I have to check why it doesn't fire first,  :)

**Comment by sharpsalat** [comment]
I made version that send to trash account messages, that really works without diconnecting.
How do you think, it is problem of Tinode or bot or grpc?
I am trying to find error in there.

**Comment by or-else** [comment]
https://github.com/grpc/grpc/issues/16038

**Comment by or-else** [comment]
https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Comment by BenDerPan** [comment]
@or-else @MyOnAsSalat  sorry for late, I added GRPC_ARG_KEEPALIVE_TIME_MS and GRPC_ARG_KEEPALIVE_TIMEOUT_MS argumnets to the Channel, and updated to the [nuget](https://www.nuget.org/packages/Tinode.ChatBot/0.15.11). 

![image](https://user-images.githubusercontent.com/10903567/50884569-2dba2f00-1426-11e9-8b7e-616cf496f403.png)

close this now, if there is any problem, feel free to reopen this issue.

**Comment by sharpsalat** [comment]
@BenDerPan Is this fix are resolving the problem of diconnecting?
I mean that if i've connected to the server i will always be connected and even if have got any error there?

**Comment by sharpsalat** [comment]
Maybe for that will better make bool parameter of constructor to do auto reconection or not.
And make event, if message doesn't sended, you received event with parameters that contains this message, in this case possible try to resend it.

**Comment by BenDerPan** [comment]
@MyOnAsSalat  now it use ping to keep connection with the server, if the server doesn't response in 2 seconds, the client will disconnect, and the disconnected event will fired. 
ChatBot will always auto reconnect when the disconnected event fired. 

```
And make event, if message doesn't sended, you received event with parameters that contains this message, in this case possible try to resend it.
```
if message doesn't sended, the failed message will be put back to the message queue and will chatbot will try to resend forever, but if the connection is down and the client reconnected, the message queue will clear.  this is because when the connection is down, the chabot have to login in and sub topic again, 
and the old message maybe not you want.  there is still a lot of room for improvement. 
I think you can make a new issue with this feature. and we can add it as the next release. forgive my poor english.  :)

**Comment by BenDerPan** [comment]
@MyOnAsSalat  the implementation with fail-resend:
![image](https://user-images.githubusercontent.com/10903567/50889963-3285df80-1434-11e9-9474-845ffb3ba607.png)
