### ISSUE TITLE
Multiple bots in one app

### ISSUE THREAD

**Issue by sharpsalat** [tinode/csharpbot#7]
Hello, is it possible to use multiple bots in one app?
I care about one port to using by all bots. Will its be in conflict?

**Comment by BenDerPan** [comment]
@MyOnAsSalat  of course you can do that by a little change, in chatbot, it will start a server to accept plugin requests, and now each ChatBot instance will create a Plugin Server, so, if you want to allow mutiple bots, you can change the ChatBots to share a same Plugin Server or just remove the plugin server if you don't need it(I just keep the interface as tinode, we don't use it now, maybe used in the future), it is easy:
1. Change the ChatBot Start method:
```C#
public async Task Start()
        {

            server= InitServer(); //Move InitServer to a global share or just comment it
            client = InitClient();
            SendMessageLoop();
            while (!cancellationTokenSource.IsCancellationRequested)
            {
....
```

2. Change the Stop Method:
```C#
/// <summary>
        /// stop chatbot
        /// </summary>
        public void Stop()
        {
            Log("Stopping","ChatBot is exiting...Wait a second...");
            cancellationTokenSource.Cancel();
            server.ShutdownAsync().Wait(); // Global stop or comment it
            channel.ShutdownAsync().Wait();

        }

```

**Comment by sharpsalat** [comment]
If i understand you right, i should do that:
`
//server= InitServer();
`
and that:
`
//server.ShutdownAsync().Wait();
`
and then i can create any count of bots just like this
`
for (int i = 0; i < 10; i++)
{
   Bots[i] = new ChatBot(host, local, schema: "basic", secret: account[i]);
}
`
And this will work same like i use only one bot?

**Comment by BenDerPan** [comment]
yes, and you should change the cookie file name, too. or you just login with user name and password not store the cookie file.
the code is very simple, you can read it and try everything as you want, such as  new features etc.

**Comment by sharpsalat** [comment]
Then, my Analyzer notice that in task used Thread.sleep() but should use Task.Delay().
Is it mistake or it just should be right?

**Comment by sharpsalat** [comment]
In developers chat was recommended this variant
`
 public async Task Start()
        {

           // server= InitServer();
            client = InitClient();
            SendMessageLoop();
            while (!cancellationTokenSource.IsCancellationRequested)
            {
                try
                {
                    await ClientMessageLoop();
                }
                catch (Exception e)
                {
                    Log("Connection Broken",$"Connection Closed:{e}");
                    OnDisconnected();
                    await Task.Delay(2000);
                    ClientReset();
                    client = InitClient();
                }
            }

        } 
`

**Comment by BenDerPan** [comment]
@MyOnAsSalat  It's a mistake, 👍

**Comment by BenDerPan** [comment]
close now.
